"""`make bindings` code generation (M1 收尾 / 计划书 §10 描述符单一来源).

Generates, from the descriptor tree (descriptors/):

* ``blocklib.json``      — frontend block library: module blocks,
                           IC channels, expression grammar, IC recipes;
* ``schema.json``        — JSON Schema for the Spec IR;
* ``univ_proxy.gen.h``   — generated copy of the (currently
                           hand-written) union proxy header; the
                           template will move into this repo when the
                           slot list stops being static;
* ``descriptors.md``     — human-readable parameter reference.

Everything carries a GENERATED banner; never edit the outputs by hand.
"""

from __future__ import annotations

import datetime
import json
import os
from pathlib import Path
from typing import Any, Dict, List

import yaml

from .descriptors import default_root, load_registry

_BANNER = "GENERATED by `kratos-front bindings` -- do not edit."

# IC channels understood by the universal pgen (univ_hydro.h ic_t).
# Keep in sync with ic_region_t: rho/pre/vel_*/b_* plus x.<species>.
_IC_CHANNELS: List[Dict[str, Any]] = [
    {"key": "mask", "doc": "region mask expression (default '1')"},
    {"key": "rho", "doc": "density"},
    {"key": "pre", "doc": "pressure"},
    {"key": "vel_x", "doc": "velocity x"},
    {"key": "vel_y", "doc": "velocity y"},
    {"key": "vel_z", "doc": "velocity z"},
    {"key": "b_x", "doc": "magnetic field x (mhd modules)"},
    {"key": "b_y", "doc": "magnetic field y (mhd modules)"},
    {"key": "b_z", "doc": "magnetic field z (mhd modules)"},
    {"key": "x.<species>", "doc": "species number fraction (chem modules; "
                                   "auto-normalized per cell)"},
]


def _load_yaml(path: Path) -> Any:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


# Module types registered by the universal pgen (usr_ext/universal/
# usr.cpp); each lists the NATIVE par sections it consumes.  Under
# mesh-level role scoping the GUI writes these as [R.<section>] for a
# module instantiated with role R (see univ_mesh.h scoped_input).
_MODULE_TYPES: List[Dict[str, Any]] = [
    {"type": "hydro",
     "sections": ["dynamics", "init", "ic.*", "unit",
                  "bc.expr_inflow"]},
    {"type": "mhd", "sections": ["dynamics", "init", "ic.*", "unit"]},
    {"type": "chem_hydro",
     "sections": ["dynamics", "init", "ic.*", "species_init",
                  "chemistry", "unit"]},
    {"type": "chemistry", "sections": ["chemistry"]},
    {"type": "multigrid", "sections": ["multigrid"]},
    {"type": "post",
     "sections": ["post", "post.cooling", "post.turb", "unit"]},
]

# Coupling capabilities (registry.h + couplable.h).  'parasite' is
# container-handled (not a named slot); named slots come from
# couple_slots() overrides.  Key = module type owning the coupling
# section [coupling.<its role>]; value = slot -> doc.
_COUPLINGS: Dict[str, Dict[str, str]] = {
    "chemistry": {
        "parasite": "host module role to parasite (bidirectional "
                    "q_che binding; chem_hydro/chem_mhd target)",
    },
    "post": {
        "dyn": "dynamics module role providing the flow field",
    },
}

# Allowed target module types per (declarer type, slot), mirroring the
# C++ hard errors: registry.h rejects a chemistry parasite onto anything
# but the multi-species dynamics flavors (q_che binding), and post_t::init
# throws when the dyn slot does not point at a dynamics module.
_SLOT_TARGETS: Dict[str, Dict[str, List[str]]] = {
    "chemistry": {"parasite": ["chem_hydro", "chem_mhd"]},
    "post": {"dyn": ["hydro", "mhd", "chem_hydro", "chem_mhd"]},
}

# Role names rejected by the container (registry.h reserved set):
# they collide with native section names once [R.<sec>] is remapped.
_RESERVED_ROLES: List[str] = [
    "module", "coupling", "device", "unit",
    "mesh", "boundary", "cycle", "file",
    "init", "ic", "bc", "species_init",
    "dynamics", "chemistry", "multigrid", "post", "cooling",
]


def _key_dicts(d) -> List[Dict[str, Any]]:
    return [
        {
            "name": k.name,
            "type": k.type,
            "required": k.required,
            "default": k.default,
            "doc": k.doc,
        }
        for k in d.keys.values()
    ]


def _module_blocks(reg) -> List[Dict[str, Any]]:
    """Block-library entries: the universal pgen's module types with
    parameter docs attached from the section descriptors."""
    by_section = {d.section: d for d in reg.all_descriptors()}
    blocks: List[Dict[str, Any]] = []
    for m in _MODULE_TYPES:
        params: Dict[str, Any] = {}
        for sec in m["sections"]:
            d = by_section.get(sec) or by_section.get(sec.rstrip(".*") + "*")
            if d is not None:
                params[sec] = _key_dicts(d)
        blocks.append({**m, "params": params})
    return blocks


def emit_blocklib(reg, dest: Path) -> Path:
    root = Path(default_root())
    grammar = _load_yaml(root / "expr_grammar.yaml")
    recipes_doc = _load_yaml(root / "ic" / "recipes.yaml")
    lib = {
        "generated": _BANNER,
        "generated_at": datetime.datetime.now(
            datetime.timezone.utc
        ).isoformat(),
        "grammar": grammar,
        "modules": _module_blocks(reg),
        "couplings": _COUPLINGS,
        "slot_targets": _SLOT_TARGETS,
        "reserved_roles": _RESERVED_ROLES,
        "ic_channels": _IC_CHANNELS,
        "ic_recipes": recipes_doc["recipes"],
    }
    out = dest / "blocklib.json"
    out.write_text(json.dumps(lib, indent=1) + "\n", encoding="utf-8")
    return out


def emit_schema(reg, dest: Path) -> Path:
    # Section types mirror core/kratos_spec/values.py infer_value.
    key_value = {
        "anyOf": [
            {"type": "integer"},
            {"type": "number"},
            {"type": "string"},
            {"type": "boolean"},
            {
                "type": "array",
                "items": {
                    "anyOf": [
                        {"type": "integer"},
                        {"type": "number"},
                        {"type": "string"},
                        {"type": "boolean"},
                    ]
                },
            },
        ]
    }
    known = sorted(
        {d.section[:-1] if d.section.endswith("*") else d.section
         for d in reg.all_descriptors()}
    )
    schema: Dict[str, Any] = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "kratos Problem Spec",
        "generated": _BANNER,
        "type": "object",
        "required": ["version", "sections"],
        "properties": {
            "version": {"type": "integer", "const": 1},
            "meta": {"type": "object"},
            "sections": {
                "type": "object",
                "additionalProperties": {
                    "type": "object",
                    "additionalProperties": key_value,
                },
            },
        },
        "x-known-sections": known,
    }
    out = dest / "schema.json"
    out.write_text(json.dumps(schema, indent=1) + "\n", encoding="utf-8")
    return out


def emit_proxy_h(dest: Path) -> Path:
    """univ_proxy.gen.h: generated copy of the tracked univ_proxy.h.

    The slot layout is currently static (p_dyn / p_che / p_mg[4]); when
    it becomes descriptor-driven this function will render a template
    instead of copying.
    """
    src = Path(
        os.environ.get(
            "KRATOS_FRONT_UNIVERSAL",
            os.path.expanduser("~/apps/kratos_frontend_dev/usr_ext/universal"),
        )
    ) / "univ_proxy.h"
    if not src.is_file():
        raise FileNotFoundError(
            f"univ_proxy.h not found at {src} "
            "(set KRATOS_FRONT_UNIVERSAL)"
        )
    body = src.read_text(encoding="utf-8")
    assert body.startswith("#pragma once")
    gen = (
        "#pragma once\n\n// " + _BANNER + "\n"
        "// Source of truth (for now): usr_ext/universal/univ_proxy.h\n"
        + body[len("#pragma once"):]
    )
    out = dest / "univ_proxy.gen.h"
    out.write_text(gen, encoding="utf-8")
    return out


def emit_docs(reg, dest: Path) -> Path:
    lines: List[str] = [
        "<!-- " + _BANNER + " -->",
        "",
        "# kratos par 参数参考（由描述符生成）",
        "",
        "每个 section 的键、类型、是否必填、默认值与说明。带 `*` 的 section",
        "名是通配前缀（如 `refine_region_00`）。",
        "",
    ]
    for d in reg.all_descriptors():
        lines.append(f"## [{d.section}]")
        lines.append("")
        if d.title:
            lines.append(f"{d.title}")
            lines.append("")
        lines.append("| key | type | required | default | doc |")
        lines.append("|---|---|---|---|---|")
        for k in d.keys.values():
            req = "yes" if k.required else ""
            dft = "" if k.default is None else f"`{k.default}`"
            doc = (k.doc or "").replace("|", "\\|")
            lines.append(f"| `{k.name}` | {k.type} | {req} | {dft} | {doc} |")
        lines.append("")
    out = dest / "descriptors.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def run_bindings(outdir: str) -> List[Path]:
    dest = Path(outdir)
    dest.mkdir(parents=True, exist_ok=True)
    reg = load_registry(default_root())
    return [
        emit_blocklib(reg, dest),
        emit_schema(reg, dest),
        emit_proxy_h(dest),
        emit_docs(reg, dest),
    ]
