#!/usr/bin/env bash
# Register the kratos frontend as the default handler for *.par files.
#
#   scripts/install.sh            install / refresh
#   scripts/install.sh --remove   uninstall
#
# Installs, per-user only (no sudo):
#   ~/.local/bin/kratos-front-open                 wrapper -> .venv entry point
#   ~/.local/share/mime/packages/kratos-par.xml    application/x-par glob
#   ~/.local/share/applications/KratosParEditor.desktop
# and sets KratosParEditor.desktop as the default for application/x-par.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CLI="$ROOT/.venv/bin/kratos-front"
BIN_DIR="$HOME/.local/bin"
APPS_DIR="$HOME/.local/share/applications"
MIME_DIR="$HOME/.local/share/mime"
WRAPPER="$BIN_DIR/kratos-front-open"
DESKTOP="$APPS_DIR/KratosParEditor.desktop"

if [[ "${1:-}" == "--remove" ]]; then
  rm -f "$WRAPPER" "$DESKTOP" "$MIME_DIR/packages/kratos-par.xml"
  update-mime-database "$MIME_DIR" 2>/dev/null || true
  update-desktop-database "$APPS_DIR" 2>/dev/null || true
  echo "removed"
  exit 0
fi

[[ -x "$CLI" ]] || {
  echo "missing $CLI — create the venv first:" >&2
  echo "  uv venv && uv pip install -e '.[server]'" >&2
  exit 1
}

mkdir -p "$BIN_DIR" "$APPS_DIR" "$MIME_DIR/packages"

cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# generated by kratos_frontend/scripts/install.sh
exec "$CLI" open "\$@"
EOF
chmod +x "$WRAPPER"

cp "$ROOT/scripts/kratos-par-mime.xml" "$MIME_DIR/packages/kratos-par.xml"
update-mime-database "$MIME_DIR"

sed "s|@WRAPPER@|$WRAPPER|" "$ROOT/scripts/KratosParEditor.desktop" \
  > "$DESKTOP"
update-desktop-database "$APPS_DIR" 2>/dev/null || true

xdg-mime default KratosParEditor.desktop application/x-par

echo "installed:"
echo "  $WRAPPER"
echo "  $DESKTOP"
echo "  application/x-par -> KratosParEditor.desktop"
echo "try:  kratos-front-open path/to/problem.par"
